language: java
jdk: oraclejdk8
services:
- docker
env:
  global:
    secure: "mF/LlALRVmqKKc9AaEh+tVHh5wtEC8efhCSqsdpMN88ASSEcJypAj0BSS7XUFE/CVlrUE6zsgHEdLGovMMkaWt6IubO7Ro1EULwqmA9loZ/xGxitH3sjZY3xQgfvk6pMgnHa1nxSkjxWjoFr0rPtIui3ELV3FLS70lddKPvGTjOtmZov90xZTIFCoPKv1Tr2huRCaf4syXeE66b0FRG7kpXIcyEMBL+Erxrbm0MVMk8iX7QOdpI042ulTbrp0O7uEyfxZaybuwqkQx8J4/EWm55ZiiKnW3l11tZ7tXBSYW/P+Zdz8b99SSD+XjKZN993EYJDgHlC/gAmBYWjRKz7EwmXQPMK0LFSW+cr9zpE+NuMcnxKQ9kDDlaA3rHJpjYd4XQgJHWSv+bI0mjzZ42q6CSglOGUBh7UQNhbO8sWrt+AAa5ExkQDlKGuo0mmw8EBH5S6JYevdAJqrWfKXEKEAt2fE7hN3oFzpQKGVVPTT3qI/JOLgsFWindV0JCTOPf5kHo4LEemCZmdi2os5oalqhxegrYGVCL5eBXjMWqK4vrc6gCkBmJL4nH0TkhJeNN5jlgixvm3jXqsgRG+PMEGJN69/1N0wCoKlFc1Gan+YkObe0v2Xpd5oKMR3pzfzKURh47NlgZfVpv17WEt1qN96VjnRQdn7MYRKAPuzJ9Zgvw="
addons:
  coverity_scan:
    project:
      name: puchen/starter
      description: Build submitted via Travis CI
    notification_email: pu.chen@salesforce.com
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true install
    branch_pattern: master
before_script:
- pip install --user codecov
after_success:
- codecov
