language: java
jdk: oraclejdk8
services:
- docker
env:
  global:
    secure: 5DlPCdYckljsLm+qua2WWedqWZDQG6AoW0+Zsp7s3RD5BGFjiK/OjAFm8UzKEVIBIM7yCKNUiusxfIT60cunCdcULBrYq0v0SRwabgqity1Qxhndlq79JG2b141eX/YxX5RvqJUck8m6E6ZgJp9MBPS3PYbEluVk6XPH4TP1B3Xnv24RLwkaaIH3gL8V+NTTHbkEAV7RpdQrAkblSvd+t6b4coafEkQ55Lgf1WfUfsHKd7cjBimxNg5tuMWBEy6Nf2Xv2yqlW0jI/aIKprlOwibdZJ5OfB2ximvmqMGxVTKb7Aaw1RS5ISTTyFb/lvHbfrWpLKADrtdU74cB2xkg19hCwWyUk77+9ayRyfT3PVhd8UcRnLISGasjWCKCixZHQvp5jtE6TCL+w6hzd8JzMFN1zYME4wLSv/SfHvrVDC+qID03Wm0lqWZ1by57/9FditCR2yonJ5fdtIPeP/8dwXwp6tkNABKzE0stHJgLK1+ddyjIcMZyazd3HrO2vRoHYeXGKAxcr6kmw/wJpqwODDPUeZJgQOpOZAl0/XCA4CCZ76zjIj4ePYOuyfMDj2Yy9Mfbh57rhabd7aHqJCCQiM+cdYRjSatgwRqWuOW5dxvHLvIbWK+8ej33uktJyD8q1nZgEjlZac/eBM+ikJfJakoU8OkUwtQP26zVBebRmSs=
addons:
  coverity_scan:
    project:
      name: puchen/starter
      description: Build submitted via Travis CI
    notification_email: pu.chen@salesforce.com
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true install
    branch_pattern: master
before_script:
- pip install --user codecov
after_success:
- codecov
