language: java
jdk: oraclejdk8
services:
- docker
env:
  global:
  - secure: OsiOte/4xmpW1lshqboT9bvoBzcUfozoIzi6k0BIXGO0+HoiJvVV7sYsZlkfbW5CFrRhuCPy2ihUII5cLxCbrJ63bf5S1YzzzjE939oXgvlAXo1wEGasAjOZB46drTDNCKBLUIb8GjQKVtYQW6nd0WagiS7uHTMmiHKie4jkGi9JVhOJ9+hgba+WB52MDFz2tVzaHkAXS9b4qpEJxdGLbPzSbkUWo7Uq0+K/wC+S/5tlEvvhvnkMEUUXUH33XMpQ+K5cY8J+MxALTF2SiqtakLH6H2juOVXGrmxG2Ui5WPvX+VF1p60umUhGe0JCsXhGzZAe7lT0Y12lCjms0JSZNKAwKUWE0zfF6iYZSExeBomrtsDig+xa+iG6hgK0IAHnYVFBvmqL6AQcAxXsVgvoUXnm5JysRQXzSzafPmdWKq8uQCBnqbUo1VzIxJV1Psj6Op4Di+v3yZKn//Q1MtkxtXJCNdrPQgyoj8R3epbBYExI58RJRwotUFXZl7EYYmq9VLBojd5iSLWNDa7RZcm0URlDYyh3S1BY1Wid6sH1M3AMhgLENxzwiZ/rqPvz6keMDw5Cgk/l9fgaiz4CyWUocTOBk8VzoXq3YveMV7cdoALGhIQn4eO6U/RiMmV90HVXqcLsb+3TvQWa+G1IAOWDFP3iyWnjq1Apf1DmPH1NXlg=
addons:
  coverity_scan:
    project:
      name: puchen/starter
      description: Build submitted via Travis CI
    notification_email: pu.chen@salesforce.com
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true install
    branch_pattern: master
before_script:
- pip install --user codecov
after_success:
- codecov
