language: java
jdk: oraclejdk8
services:
- docker
env:
  global:
  - secure: lCi0JH2cAcyWQGxnXh/A2naJIOjJo7kuDmwdi7qRZwHZhIGW/MyMWfuLildsdgMQTWsrm5J9J+3ThNKomRUgC4WFzFJn18rct0OdTZ+vbzzhmgNebQUMdBZxtqLs3wT61soNZLFAynwt1uDqrcvcIMLhjcwntw+M381VCDSTn5FbHWIrLyfQzEBoxOD5PhG0zS3gqEqoObI3es5MX4dZUYwbTHBOkO/NAmCgphaoB8c0A0H1KuLABPcKqgsJtFrr3zsDK7mZSyOjdlmCQnN/jeHDy1ZaJrN9JThjbT9gdqzygyEmnLnL6ORtbvsBbKxCmG/90JwaS/6YSSO9zKYIftvuugN6+iTVsCYcZgtHdqxzK8gI0VDerAGL7IhXANdmYEhvLJhO+i4m9AHiCvmC3jurePzUAZtQ3KUGmRjz40dtDD/hRLTYjPT709QmKg8YheEqZGHnxHauH756muWqszNucXc+yRuEdjvG6kqpJNGxI5mYpGcdsfqy5CMmLOF8oXhuEmoPk/iSJnTCMTDEaJZA67JVojqyPb/93+dt9K/TZTCHw8Di2MlqHyxCZgki2Y3LOlxuoarQEpbKnxJf370R+BTOgTZJHEdXKSHT/4y3j1HfkiMsulYqiwvqvK+Y8RmxWhyAVt+Na8w2tprihxUdTEVKha1tTPnF/u2WTa0=
addons:
  coverity_scan:
    project:
      name: puchen-sfdc/starter
      description: Build submitted via Travis CI
    notification_email: pu.chen@salesforce.com
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true install
    branch_pattern: master
before_script:
- pip install --user codecov
after_success:
- codecov
