language: java
jdk: oraclejdk8
services:
- docker
env:
  global:
  - secure: m7sft7lU+7sCuCksA2/2foZYEp7P0CGYqjH695PFNbg7iQffXJnqvmFffVkRM7lZAvqk+J1Lu5kiVBGBDNTztslgYl/QwOnQN53ENc07z/oPtDxNUELCwsEvA716b1HScp/Wciq4b0RhxwgEqd3vKw/60vUZJ1tipEVX3rg4BMu+PdRWTGiN3J0Wkf3ojg/NPzXcwQ6Qje5FqfgJMDyJKzCjfmWUfX+6LdaeUx0xtNDgJboc3YNdxquqWlhm1jk3H5V7IBCoCtPhN2JJJZvdfsKpDs08tVbRaiQATUgI1W/kLEAqcSjcFEmEmZcnRx1M1H1faqi/+/2/+qsR4xRfdBJw/k+m8iUh0bWTXgvBj0NDpPkhRUqhPalJM3ZMGCbOiXxjHUnT90W9/mpujsTL8gi6KYfluNZb1JYCbIUqfMe12LXoef3KOSf0dydh3tVuzcldM2r+ENQ7PIDwo/Dxiw5+i08s+7KFwsyGCZoUVBuujmcIyNpPVjqoPCp/IWFAhfDMu3zXgSahMGUefX1FjO2J2qnw7tnUPsi+2EVWjhxTXb0VTkdbQFwXKoRwmUm5MQ8dckIk6bAGAAi5tYFg2ZWUlSYwoaQR+xVzI0zLUUPV4npnwwEdqTR0hJwRjKcP08WhYgs0aVD82BXZ8pbeQHYuwbQcMhu8NAh58s0D7Mg=
addons:
  coverity_scan:
    project:
      name: puchen/starter
      description: Build submitted via Travis CI
    notification_email: pu.chen@salesforce.com
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true install
    branch_pattern: master
before_script:
- pip install --user codecov
after_success:
- codecov
